### PR TITLE
Sir prefix for knight

### PR DESCRIPTION
**Pull request by morrowwolf**
Should give some authority and weight to a knight screaming for help or coordinating witch hunts.

### CODE REVIEW

**Comment by Altoids1** [comment]
This would mean that peasants that steal the kit of a dead knight and pretend to be a knight themselves would then be immediately spotted based on their name, in a kinda goofy vaguely-metagamey way.

**Comment by morrowwolf** [comment]
Hypothetically everyone would know everyone in town and their voices

**Comment by Parune** [comment]
If you want to avoid calling women 'Sir' (this is a big problem in Baystation), I'd recommend using the prefix 'Dame' for females.  Nothing in history has really equaled knighthood in the militaristic sense for women, so damehood's probably the closest you're going to get.  Alternatively, a new system of prefixes could be formulated for both sexes if you people were feeling creatively bold.

**Comment by morrowwolf** [comment]
If the creative department gets me a new naming system by the time I get to fixing this and merging it then for sure.

At the same time it might create some confusion.

**Comment by morrowwolf** [comment]
Altoids: the guy who fixes problems that aren't there.

I'd prefer to leave it "broken" so if it does happen it can easily be identifiable as no one _should_ be non-binary in the game.

But do your memes and ignore the ovens....

**Pull request merged**
