### PR TITLE
The baseturf is now dirt. Diggers, rejoice

### LINKED ISSUE #117: Shoveling grass creates plating and sand
image

Need to either set or create a dirt baseturf that can't be removed.

### PR DESCRIPTION
**Pull request by ike709**
Fixes #117 

It is now safe to map in shovels.
image

### CODE REVIEW

**Comment by morrowwolf** [comment]
I think that dirt plating is the one that consumed oxygen and suffocated everyone that one test 🤔

**Comment by ike709** [comment]
I fixed that.

**Comment by morrowwolf** [comment]
You the best :finger_guns:

**Comment by ike709** [comment]
image

**Pull request merged**
