### PR TITLE
Python scripting

### PR DESCRIPTION
**Pull request by morrowwolf**
Straight stolen from: https://github.com/yogstation13/Yogstation-TG/pull/2420

Guide from what I understand: https://hackmd.io/waVJrS_nSSePbJ8jfuN4nA#

Needs testing and everything to be run right now

### CODE REVIEW

**Comment by morrowwolf** [comment]
This shit all seems to work which is good.  Not 100% sure what I would use it for but I'm interested none the less.

**Comment by morrowwolf** [comment]
Leaving this for next week.

**Comment by k-k-karma** [comment]
enjoy the security holes and errors from a slow interperter

**Comment by morrowwolf** [comment]
Just leaving it for now, I don't know it well enough to fix anything by myself and I can't seem to find a reason for it yet.

Gonna wait for Mac to come back or until I find a reason for it before actually merging.

**Comment by morrowwolf** [comment]
We can always reopen later at some point.

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
darn

**Pull request closed without merging**
