### PR TITLE
Implements Ovens

### LINKED ISSUE #43: Ovens to cook shit need to be implemented

### PR DESCRIPTION
**Pull request by Altoids1**
Wow ovens wow!

Closes #43

### CODE REVIEW

**Comment by morrowwolf** [comment]
Maybe put it under obj/structure instead of something completely new?

Probably best to add our own "oven_act()" so we can customize what we want and make absolutely sure we have at least looked over what's being used in the game.

**Comment by DLCabbose** [comment]
wow

**Comment by morrowwolf** [comment]
While you're at it fix your DME, it's trying to overwrite the whole thing.

**Comment by Altoids1** [comment]
Fixed the DME

**Comment by Altoids1** [comment]
As for the plate business, I'ma just file it under #76 and leave @Parune to it.

**Comment by morrowwolf** [comment]
`[17:53:03] Runtime in snacks.dm,273: undefined variable /obj/structure/medieval/oven/var/dirty
  proc name: microwave act (/obj/item/reagent_containers/food/snacks/microwave_act)
  usr: MorrowWolf/(Dame Kaiden Ann)
  usr.loc: (Barony Inside (10, 36, 2))
  src: the meat steak (/obj/item/reagent_containers/food/snacks/meat/steak/plain)
  src.loc: the oven (/obj/structure/medieval/oven)
  call stack:
  the meat steak (/obj/item/reagent_containers/food/snacks/meat/steak/plain): microwave act(the oven (/obj/structure/medieval/oven))
  the oven (/obj/structure/medieval/oven): cook()
  the oven (/obj/structure/medieval/oven): startcook()
  the oven (/obj/structure/medieval/oven): attack hand(Dame Kaiden Ann (/mob/living/carbon/human))
  Dame Kaiden Ann (/mob/living/carbon/human): UnarmedAttack(the oven (/obj/structure/medieval/oven), 1)
  Dame Kaiden Ann (/mob/living/carbon/human): ClickOn(the oven (/obj/structure/medieval/oven), "icon-x=18;icon-y=4;left=1;scre...")
  the oven (/obj/structure/medieval/oven): Click(the floor (9,37,2) (/turf/open/floor/wood), "mapwindow.map", "icon-x=18;icon-y=4;left=1;scre...")
`
I put a cooked steak into the oven again and this runtime happened.

Also you can rapidly click on the oven while cooking and you end up with
"That's an oven
Cooks and boils things.
There seems to be enough wood in the oven to cook about -23 things.
You can see a meat steak in the oven."

when you examine.

**Comment by morrowwolf** [comment]
Examine should also describe the capabilities of the oven.  You should be able to take something out without cooking etc.

**Pull request merged**
